error: add new PycloudlibQuotaError to propagate quota errors
For the user to be able to retry on quota error, we need to be able to
propagate this exception.